config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :actors
   resources :movies do
     get 'rate'
   end 
   resources :users
   root :to => "movies#index"

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :movie_actors, dependent: :destroy
  has_many :movies, through: :movie_actors
#  validates :name,presence:true,uniqueness:true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
   has_many :songs, dependent: :destroy
   has_many :movie_actors, dependent: :destroy
   has_many :actors, through: :movie_actors
   has_many :ratings, as: :rateable
#   validates :description, presence:true
#    validate :check_name, uniqueness:true
     validates :name, uniqueness:true
#   validates :rating, numericality:true
#   before_validation :check_ratings
#    before_save :check_caps 
    validate  :check_caps
#   after_save :check_save
#   after_update :check_update

  accepts_nested_attributes_for :songs, :movie_actors, allow_destroy: true
   def check_caps
     caps = 'A'..'Z'
     if !caps.include?(self.name[0])
       self.name = self.name.upcase  
       self.errors.add(:name,'error') 
     end
   end

   def check_update
     p "record updated"
   end
   def check_save
     p "record saved"
   end

   def check_ratings
     self.rating = 5 if rating.nil?
   end
   def check_name
    errors.add(:name, 'Change name') if name != 'Pratik'
  end
end

app/models/movie_actor.rb
class MovieActor < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :rateable, polymorphic: true
  validates :stars, numericality:true
  validates :user_id, presence:true 
  validate :one_five
  validates_associated :user
  def one_five
    if !(0..5).include?self.stars
    self.errors.add(:stars,'wrong no of stars')
    end
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
   belongs_to :Movie
   has_many :ratings, as: :rateable
#   validates :movie_id,presence:true
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ratings
#  validates :id,presence:true
#  validates :name,presence:true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
   @actors=Actor.all
  end
  def show
    @actor=Actor.find(params[:id])
    @movies= @actor.movies
  end
  def edit
    @actor=Actor.find(params[:id])
    
  end
  def create
    
    @actor=Actor.new(actors_params)
    if @actor.save
      redirect_to actors_path
    else
      render action: 'new'
    end
   # p params[:actor]
  end

  def actors_params
    puts params.require(:actor).permit(:name)
    params.require(:actor).permit(:name)
  end
  def new
    @actor = Actor.new
  end
  def del
   
  end
  def destroy
    @ac = Actor.where(id:params[:id])
    @ac[0].destroy
    redirect_to actors_path
  end
  def update
    ac = Actor.find(params[:id])
    ac.name=params[:ac_name] 
    if ac.save 
      redirect_to actors_path
    else
      render action: 'edit'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
  def edit
    @movie = Movie.find(params[:id])
    @actor = Actor.all
  end
  def update 
    @movie = Movie.find(params[:id])  
    if params[:stars] > 0
      p "done"  
    else
      if @movie.update_attributes(movies_params)
        redirect_to movies_path
      else
        render action: 'edit'
      end
    end
  end

  def new
    @movie = Movie.new
    @actor = Actor.all
  end
  def show 
    
    @movie_rate=Rating.new
    @movie = Movie.find(params[:id])     
    @songs = @movie.songs 
    @actors = @movie.actors

    rating= current_user.ratings.where(rateable: @movie)[0]
    
    @rated = -1
    if rating.present?
      @rated = rating.stars
    end

  end
  def create
      @movie = Movie.new(movies_params)
    if @movie.save
      redirect_to movies_path
    else
      render action: 'new'
    end 
  end
  def movies_params
     params.require(:movie).permit(:name,songs_attributes: [:id, :name, :_destroy ],movie_actors_attributes: [:id,:actor_id, :name, :role,:_destroy])
#,{:songs_attributes => [:name,:_destroy]})
  end
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  def rate
    # save in database
    
    @movie = Movie.find(params[:movie_id])
    #p current_user
    current_user.ratings.create(stars: params[:stars], rateable: @movie)
    #render nothing: true
  #  render  action: 'show'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end
  def show
    p params[:name]
    user1 = User.where(name:params[:name])
    p user1
    total = 10
    @rating_movie = Array.new
    @rating_song = Array.new
#    @user = User.find(params[:id])
    @user = user1[0]
    @movies = Movie.all
    @songs = Song.all
    
    @movies.each do |movie|
      rate_sum = 0
      total = 0
      rate = movie.ratings
      rate.each do |r|
        rate_sum = rate_sum+r.stars
        total = total + 1
      end
      if total > 0
        @rating_movie.push(rate_sum/total)
      else
        @rating_movie.push(0)
      end
    end

    
    @songs.each do |song|
      rate_sum = 0
      total = 0
      rate = song.ratings
      rate.each do |r|
        rate_sum = rate_sum+r.stars
        total = total + 1
      end
      if total > 0
        @rating_song.push(rate_sum/total)
      else
        @rating_song.push(0)
      end
    end
  end
  def new
    @rating = Rating.new
  end
  def edit
     @rating=Rating.new
  end

  def create
    @user = User.find(params[:user_id])
    p @user.name
    if params[:type] == 'Movie'
       if @user.ratings.create(stars:params[:stars],rateable:Movie.find(params[:id]))
         p params[:stars]
         p "movie"
         redirect_to user_path(@user,name:@user.name)
       else
         render action: 'edit'
       end
    else
       if @user.ratings.create(stars:params[:stars],rateable:Song.find(params[:id]))
         p "song"
         redirect_to users_path(@user,name:@user.name)
       else
         render action: 'edit'
       end
    end
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/create.html.erb
this is my create

app/views/actors/del.html.erb
choose the actor to delete

app/views/actors/delete.html.erb
This is my Delete

app/views/actors/destroy.html.erb
Actor Deleted

app/views/actors/edit.html.erb
<%= form_tag(actor_path, method: "put") do%>
   New Name: <%= text_field_tag(:ac_name) %>
  <%= submit_tag("Update") %>
  <% end %>

app/views/actors/index.html.erb
<html>

  Welcome to my World

  <%= rand(10)%>
  <% a=Actor.all;%>
  <%  @actors.each do |i|%> 
  <p><%=link_to i.name,i %></p>
  <% end%>

  <%= form_tag("/actors", method: "post") do %>
  
  <%= text_field_tag(:act_name) %>
  <%= submit_tag("Enter") %>
  <% end %>
  <%=link_to "new",new_actor_path%>
  





  </html>

app/views/actors/new.html.erb
<%= form_for @actor, url:actors_path do |f| %>
  
  <%=  @actor.errors.full_messages unless @actor.errors.empty? %>
  
  <%= f.label :name  %>
  <%= f.text_field :name %>
  <%= f.submit "Save" %>
<% end %>

app/views/actors/show.html.erb
<%=@actor.name %><BR>
MOVIES DONE:


<% @actor.movie_actors.includes(:movie).each do |movie_actor| %>
	<%= movie_actor.role %>
	<%= movie_actor.movie.name %>
<%end%>


<%= link_to("delete",actor_path,method: :delete)%>
<%= link_to("update",edit_actor_path,method: :get)%>


<%#= form_for @actors, url:update_actor_path do |f| %>
  <%#= f.text_field :ac_name %>
  <%#= f.submit "Update" %>
<%# end %>

app/views/actors/update.html.erb
Record updated!!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FionaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%if user_signed_in?%>
<%=link_to "logout",destroy_user_session_path, method:'delete'%>
<%else%>
<%= link_to "User Login", new_user_session_path%>
<%end%>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%=simple_nested_form_for @movie  do |f| %>
  <%=f.input :name%>
  <%= f.fields_for :songs do |song| %>
    <%= song.input :name %>
    <%= song.link_to_remove "delete song" %>
  <% end %>
<p><%= f.link_to_add "Add song", :songs%></p>

  <%= f.fields_for :movie_actors do |actor|%>
     <%#= actor.collection_select :name,Actor.order(:name),:id,:name, include_blank: true%>
     <%=actor.association:actor%>
     <%=actor.input:role%>
     <%= actor.link_to_remove "delete actor" %>
  <% end %>
<p><%= f.link_to_add "add actor", :movie_actors%></p>

  <%=f.button :submit%>



<%end%>

app/views/movies/edit.html.erb
<%=render partial: "form"%>

app/views/movies/index.html.erb
<h1>IMDB</h1>

<%= link_to "Create_new_movie",new_movie_path%>
<hr>
<%= link_to "View_actors", actors_path%>
<hr>
<%= link_to "View_users", users_path%>
<%if user_signed_in?%>
<p><%= link_to "rate", movies_path%></p>
<%end%>
<hr>
<%  @movies.each do |movie| %>
  <p><%=link_to movie.name,movie %>
  <%=link_to("delete",movie_path(movie),method: :delete)%>
  <%= link_to("update",edit_movie_path(movie),method: :get)%>
</p>
<%end%>

app/views/movies/new.html.erb
<%=render partial: "form"%>

app/views/movies/rate.html.erb
This is  a test rate

<%= user_session%>

app/views/movies/show.html.erb
<h1><p><%= @movie.name%></p><h1>
<hr>

<script>
  var movie_id = "<%= @movie.id %>"   
</script>

<%= label_tag :rate_movie %>
<% if @rated > 0 %>
  <%= label_tag :star,@rated%>
  <% else%>
  <%= select_tag :stars, options_for_select(1..5)%>
    <%= link_to "rate", "javascript:void(0)", id: "link_rate" %>
<%end%>

<p><%=@movie.description%></p>

<h2>Songs:</h2>
<hr>
  <% @songs.each do |song|%>
    <p>  <%= song.name%></p>
  <%end%>

<h2>Cast:</h2>

  <hr>
  <%i = 0%>
  <% @actors.each do |actor|%>
    <p>  <%= actor.name%> <%=@role; i = i+1%></p>

  <%end%>
 

app/views/users/edit.html.erb
<p>TYPE:<%= params[:type]%></p>
<p>USER_ID:<%= params[:user_id]%></p>
<p>MOVIE_ID:<%= params[:id]%></p>


<%= form_for @rating, url:users_path(:user_id => params[:user_id],:type => params[:type],:id => params[:id]) do |f| %>
  Enter stars:
  <%= f.text_field :stars %>
  <%= f.submit "Save" %>
<% end %>

app/views/users/index.html.erb
<h1>Welcome</h1>
<hr>
<!--Choose User:-->
Enter User Name:
<hr>
<%# @users.each do |user|%>
 <p> <%#= link_to user.name,user%> </p>
<%#end%>


  <%= form_tag(user_path(id:1), method: "get") do %>

  <%= text_field_tag(:name) %>
  <%= submit_tag("Enter") %>
  <% end %>
  <%= link_to "new_user","new_user.html.erb"%> 



<%#= form_for @user, url:user_path(id:1),method: 'GET' do |f| %>
  <%#= f.text_field :name %>
  <%#= f.submit "Validate" %>
<%# end %>

app/views/users/new.html.erb
Enter stars:
<p>TYPE:<%= params[:type]%></p>
<p>USER_ID:<%= params[:user_id]%></p>
<p>MOVIE_ID:<%= params[:id]%></p>


<%= form_tag(users_path(:user_id => params[:user_id],:type => params[:type],:id => params[:id]), method: "post") do%>
   Enter Stars: <%= text_field_tag(:stars) %>
  <%= submit_tag("Rate") %>
  <% end %>

~                                    

app/views/users/show.html.erb
<%= javascript_tag do %>
$(document).ready(function() {
  window.$M = new (MyApp.<%= params[:controller].capitalize %> || MyApp.Base)();
  if (typeof $M.<%= params[:action] %> === 'function') {
    return $M.<%= params[:action] %>.call();
  }
});
<% end %>


<h1>Welcome
<%=@user.name%>
</h1>
<h1>Rate Movies:</h1>
<hr>
<%i=0%>
<% @movies.each do |movie|%>
<p> <%= link_to movie.name,new_user_path(:id =>movie.id,:user_id => params[:id],:type => 'Movie')  %> <%=@rating_movie[i] %>
<%i = i+1%>
<%end%>
<h1>Rate Songs:</h1>
<%i=0%>
<% @songs.each do |song|%>
<p> <%= link_to song.name,new_user_path(:id =>song.id,:user_id => params[:id],:type => 'Song')%> <%=@rating_song[i]%>
<%i=i+1%>
<%end%>